sudo: false

language: python
python:
  - "3.5.3"
branches:
  only:
    - master

install:
  - pip install -r requirements.txt
  - pip install .

script: python -m pytest --cov=bermuda test/ && coveralls